### ISSUE TITLE
playlist_edit do not match API features

### ISSUE THREAD

**Issue by aleagudom** [ampache/python3-ampache#15]
Current playlist_edit function can only modify 'name' and 'type', but actually, the API also allows changing the owner and songs.
This is very useful for filling a recently created playlist with songs in bulk.

I've locally modified ampache.py and it's working for me

Please, note, I'm passing items and tracks as lists for convenience. But, could have more sense to let them as strings for coherence.

    def playlist_edit(self, filter_id: int, name=False,
                      object_type=False, owner=False,items=False, tracks=False):
        """ playlist_edit
            MINIMUM_API_VERSION=400001

            This modifies name and type of a playlist

            INPUTS
            * filter_id   = (integer)
            * name        = (string) playlist name //optional
            * object_type = (string) 'public'|'private' //optional
            * owner       = (string) owner id //optional
            * items       = (list) song_id's list //optional
            * tracks      = (list) track numbers list //optional
        """
        items_str = ','.join(items)
        tracks_str= ','.join(tracks)
        ampache_url = self.AMPACHE_URL + '/server/' + self.AMPACHE_API + '.server.php'
        data = {'action': 'playlist_edit',
                'auth': self.AMPACHE_SESSION,
                'filter': filter_id,
                'name': name,
                'type': object_type,
                'owner': owner,
                'items': items_str,
                'tracks': tracks_str}
        if not name:
            data.pop('name')
        if not object_type:
            data.pop('type')
        if not owner:
            data.pop('owner')
        if not items:
            data.pop('items')
        if not tracks:
            data.pop('tracks')

        data = urllib.parse.urlencode(data)
        full_url = ampache_url + '?' + data
        ampache_response = self.fetch_url(full_url, self.AMPACHE_API, 'playlist_edit')
        if not ampache_response:
            return False
        return self.return_data(ampache_response)

**Comment by lachlan-00** [comment]
thanks, i can mis these sometimes i'll update the function now. the object_type parameter name is wrong so i'll rename to make it fit too
