### ISSUE TITLE
json support

### ISSUE THREAD

**Issue by lachlan-00** [ampache/python3-ampache#3]
@AshotN i've started merging json into the repo.
![image](https://user-images.githubusercontent.com/1305249/73226578-59888e00-41bc-11ea-8bac-1090f889be81.png)

annoyingly json in python is much simpler than xml!

**Comment by AshotN** [comment]
So JSON does or doesn’t work well with Python

**Comment by lachlan-00** [comment]
Really well, the default json lib converts objects into dictionaries making the code really simple

**Comment by lachlan-00** [comment]
@ashotn json is basically ready. I've been going through and fixing things as I see them. Not really an issue any more as it works. I'll keep updating the examples and responses
