### ISSUE TITLE
total_count required for json

### ISSUE THREAD

**Issue by lachlan-00** [ampache/python3-ampache#4]
hey @AshotN 
there's a difference between xml/json where xml returns a total count item. in python i can just count the items for a count but should this be included in json_data?

![image](https://user-images.githubusercontent.com/1305249/73899412-4a01f700-48d8-11ea-83d5-fd105459e8ed.png)

**Comment by AshotN** [comment]
I opted on leaving that out, as it's a waste of data. The client can easily count the number of objects in the array. If you want we can add it, but I really don't see a purpose in adding random metadata.

**Comment by lachlan-00** [comment]
that's fine with me, i thought the same thing.
