### ISSUE TITLE
get_art() - "destination" parameter missing

### ISSUE THREAD

**Issue by stubbornGarrett** [ampache/python3-ampache#5]
The get_art() function is missing the "destination" parameter.
Same applies for the description.

https://github.com/ampache/python3-ampache/blob/768416b010133b4cb6f6e3f0079fccd4d54674c1/src/ampache.py#L2227-L2241

With kind regards

**Comment by lachlan-00** [comment]
just going through final checks on 4.2.0 and this is added. just testing out the actual results now
